services:
  task_mongodb:
    image: mongo:6.0.4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: task_store
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: